name: note build
# 触发workflow的条件
on:
  push:
    # 只有master分支发生push事件时，才会触发workflow
    branches: 
      - main
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
  pull_request:
    branches: [main]
    

# jobs表示执行的一项或多项任务
jobs:
  deploy: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: '22' # SSH端口
          FOLDER: ./ # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SERVER_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.USER_NAME }} # 引用配置，服务器登录名
          SERVER_DESTINATION: /home/lighthouse/blog/ # 部署到目标文件夹

      - name: Restart server # 第三步，重启服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.ACCESS_TOKEN }}
          key: ${{ secrets.USER_NAME }}

      - uses: actions/setup-node@v1
        with:
            node-version: v14.17.0

      #缓存依赖
      - name: Cache nodemodules
        uses: actions/cache@v1
        env:
            cache-name: cache-node-modules
        with:
            # 需要缓存的文件的路径
            path: ./node_modules 
            # 对缓存的文件指定的唯一标识
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }} 
            # 用于没有再找目标key的缓存的backup选项
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-

      # 装依赖
      - name: Install
        run: yarn

      # 打包
      - name: Build
        run: yarn build
                  

                
